### PR TITLE
chore: update pfp

### PR DESCRIPTION
**Pull request by gifaldyazkaa**
Finally, new pfp is here! 🎉

### CODE REVIEW

**Comment by gifaldyazkaa** [comment]
bentar, sebelum merge, mari kita keluarkan kata kata wangy dlu :v

**Comment by gifaldyazkaa** [comment]
SHIROKO ......... SHIROKO SHIROKOOOOOOOOOOO AAAAAAAAAAAAAAAAAAAAAAAGH ❤ ❤ ❤ ❤ WANGI WANGI WANGI WANGI HU HA HU HA HU HA, aaaah baunya shiroko wangi aku mau nyiumin aroma wanginya shiroko AAAAAAAH ~~ Rambutnya.... aaah rambutnya juga pengen aku elus-elus ~~~~~ AAAAAH SHIROKO keluar pertama kali juga manis ❤ ❤ ❤ dia pas ngedesah juga manis banget AAAAAAAAH SHIROKO LUCCUUUUUUUUUUUUUUU............ GUA BAKAL BAKAR DUIT 12 JUTA RUPIAH BUAT SHIROKO AAAAAAAAAAAAAAAAAAAAAAAAAAAAGH ❤ ❤ ❤ apa ? SHIROKO itu gak nyata ? Cuma karakter 2 dimensi katamu ? nggak, ngak ngak ngak ngak NGAAAAAAAAK GUA GAK PERCAYA ITU DIA NYATA NGAAAAAAAAAAAAAAAAAK BANGSAAAAAT !! GUA GAK PEDULI SAMA KENYATAAN POKOKNYA GAK PEDULI. shiroko ngeliat gw ... SHIROKO di laptop ngeliatin gw. ❤ ❤ ❤  shiroko ... kamu percaya sama aku ? aaaaaaaaaaah syukur shiroko gak malu merelakan aku aaaaaah ❤ ❤ ❤ YEAAAAAAAAAAAH GUA MASIH PUNYA SHIROKO HU HA HU HI HU HA HU HI AKU SAYANG AKU CINTA SHIROKO AKU SUAMII SHIROKOOO

**Comment by gifaldyazkaa** [comment]
:v

**Comment by gifaldyazkaa** [comment]
Halo teman2ku semuanya,
  
Jika andai kata saya bisa meminta doa dari kalian semua, tolong doain ya bang malem ini saya bisa bermimpi pala saya dijepit ama PAHANYA SHIROKO YANG BONTOT BANGET GILA MEN GATAHAN GUE LIAT PAHA SEGEDE GITU GIMANA KALO KEDUA TANGAN GUE INI COBA UNTUK NGEREMESNYA TRUS KEDUA TELINGA GUE NGERASAIN BETAPA HALUSNYA KULIT PAHA THICC AF YANG SHIROKO PUNYA MUNGKIN BISA JADI SEBUAH ANUGERAH UNTUK GUE BISA MIMPIIN DIA MALEM

INI SUMPAH MEN GILA MANTEP BANGET,
GUA PENGEN BANGET DIJEPIT PAHANYA SHIROKOOOOOOOOOOO

**Comment by gifaldyazkaa** [comment]
aowkaowkoakwo, dah dah :v

**Comment by gifaldyazkaa** [comment]
mntp stress. gws to myself 🎉

**Comment by gifaldyazkaa** [comment]
See raw image here
[cdn.upload.systems/uploads/m47Lb7Pr.png](https://cdn.upload.systems/uploads/m47Lb7Pr.png)

**Comment by shiraayuki** [comment]
> SHIROKO ......... SHIROKO SHIROKOOOOOOOOOOO AAAAAAAAAAAAAAAAAAAAAAAGH ❤ ❤ ❤ ❤ WANGI WANGI WANGI WANGI HU HA HU HA HU HA, aaaah baunya shiroko wangi aku mau nyiumin aroma wanginya shiroko AAAAAAAH ~~ Rambutnya.... aaah rambutnya juga pengen aku elus-elus ~~~~~ AAAAAH SHIROKO keluar pertama kali juga manis ❤ ❤ ❤ dia pas ngedesah juga manis banget AAAAAAAAH SHIROKO LUCCUUUUUUUUUUUUUUU............ GUA BAKAL BAKAR DUIT 12 JUTA RUPIAH BUAT SHIROKO AAAAAAAAAAAAAAAAAAAAAAAAAAAAGH ❤ ❤ ❤ apa ? SHIROKO itu gak nyata ? Cuma karakter 2 dimensi katamu ? nggak, ngak ngak ngak ngak NGAAAAAAAAK GUA GAK PERCAYA ITU DIA NYATA NGAAAAAAAAAAAAAAAAAK BANGSAAAAAT !! GUA GAK PEDULI SAMA KENYATAAN POKOKNYA GAK PEDULI. shiroko ngeliat gw ... SHIROKO di laptop ngeliatin gw. ❤ ❤ ❤ shiroko ... kamu percaya sama aku ? aaaaaaaaaaah syukur shiroko gak malu merelakan aku aaaaaah ❤ ❤ ❤ YEAAAAAAAAAAAH GUA MASIH PUNYA SHIROKO HU HA HU HI HU HA HU HI AKU SAYANG AKU CINTA SHIROKO AKU SUAMII SHIROKOOO

stress

**Comment by gifaldyazkaa** [comment]
@shiraayuki awokaowkaowk yamaap mbak

**Comment by gifaldyazkaa** [comment]
Stress di sosmed ❌
Stress di GitHub ✅

**Pull request merged**
